const flagMapping: Record<string, string> = {
  'México': 'mx',
  'Sudáfrica': 'za',
  'Rep. Corea': 'kr',
  'Corea del Sur': 'kr',
  'Rep. Checa': 'cz',
  'Canadá': 'ca',
  'Bosnia': 'ba',
  'Bosnia y Herzegovina': 'ba',
  'EEUU': 'us',
  'Estados Unidos': 'us',
  'Paraguay': 'py',
  'Catar': 'qa',
  'Suiza': 'ch',
  'Brasil': 'br',
  'Marruecos': 'ma',
  'Haití': 'ht',
  'Escocia': 'gb-sct',
  'Australia': 'au',
  'Turquía': 'tr',
  'Alemania': 'de',
  'Curazao': 'cw',
  'Países Bajos': 'nl',
  'Japón': 'jp',
  'C. Marfil': 'ci',
  'Costa de Marfil': 'ci',
  'Ecuador': 'ec',
  'Suecia': 'se',
  'Túnez': 'tn',
  'España': 'es',
  'Cabo Verde': 'cv',
  'Bélgica': 'be',
  'Egipto': 'eg',
  'A. Saudí': 'sa',
  'Arabia Saudí': 'sa',
  'Arabia Saudita': 'sa',
  'Uruguay': 'uy',
  'Irán': 'ir',
  'N. Zelanda': 'nz',
  'Nueva Zelanda': 'nz',
  'Francia': 'fr',
  'Senegal': 'sn',
  'Irak': 'iq',
  'Noruega': 'no',
  'Argentina': 'ar',
  'Argelia': 'dz',
  'Austria': 'at',
  'Jordania': 'jo',
  'Portugal': 'pt',
  'RD Congo': 'cd',
  'R.D. Congo': 'cd',
  'Inglaterra': 'gb-eng',
  'Croacia': 'hr',
  'Ghana': 'gh',
  'Panamá': 'pa',
  'Uzbekistán': 'uz',
  'Colombia': 'co',
};

export function getFlagUrl(countryName: string): string {
  const code = flagMapping[countryName.trim()];
  if (!code) {
    return 'https://flagcdn.com/w40/un.png'; // Fallback to UN flag
  }
  return `https://flagcdn.com/w40/${code}.png`;
}
